### ISSUE TITLE
The latest release is not on `rfsber.home.xs4all.nl`

### ISSUE THREAD

**Issue by chenrui333** [gumpu/ROBODoc#20]
👋  just a friendly reminder that the release source archive did not get uploaded `https://rfsber.home.xs4all.nl/Robo/archives/`, not quite sure if that is intentional or not.  Thanks!

**Comment by chenrui333** [comment]
Also project homepage needs to be updated as well
![image](https://user-images.githubusercontent.com/1580956/106365958-ddf97980-6306-11eb-9be5-042bffadb96a.png)

```
$ curl -I https://www.xs4all.nl/~rfsber/Robo/index.html
HTTP/2 301
date: Sat, 30 Jan 2021 19:21:10 GMT
server: Apache
x-frame-options: SAMEORIGIN
location: https://rfsber.home.xs4all.nl/Robo/index.html
cache-control: max-age=0
expires: Sat, 30 Jan 2021 19:21:10 GMT
content-type: text/html; charset=iso-8859-1
```

relates to https://github.com/Homebrew/homebrew-core/pull/70030

**Comment by gumpu** [comment]
Thanks! Had forgotten about those.

**Comment by gumpu** [comment]
Fixed.

**Comment by chenrui333** [comment]
Thanks!
